spring:
  config:
    import: classpath:integration.yml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 1234
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      jakarta:
        persistence:
          validation:
            mode: none
    show-sql: false
  redis:
    port: 6739
server:
  tomcat:
    relaxed-query-chars: <,>,[,\,],^,`,{,|,}
